### PR TITLE
Update extensions_lib_agents.conf

### PR DESCRIPTION
**Pull request by alafarcinade**
In agentstaticlogin/status_logged, Playback should better be executer after the function key state toggle.
This to avoid to get off keys with a loggued agent (in case of the agent hangs up before the end of agentloginok playback)

### CODE REVIEW

**Comment by sboily** [comment]
Thanks Alex :)

**Comment by alafarcinade** [comment]
You welcome ... 1st Pull request (not so easy) ...

**Comment by sboily** [comment]
Congrats ! Now you will be ready to contribute a lot to xivo ! :)

**Comment by elessard1** [comment]
Pull requests should not be merged into the master branch during the freeze period.

**Pull request merged**
